[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'tests'
cache_path  = 'cache_forge'
optimizer = true
optimizer_runs = 100_000
solc='0.8.24'
evm_version= 'shanghai'

[rpc_endpoints]
base = "${RPC_URL_BASE}"
